---
require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6

# Layout/EndOfLine:
#   Enabled: false
  
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - specs/**/*
    - Rakefile

Metrics/LineLength:
  Enabled: true
  Exclude:
    - specs/**/*

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - specs/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - app/db/migrations/**/*
    - Rakefile

Style/Not:
  Enabled: true
  Exclude:
    - app/policies/**

Style/AndOr:
  Enabled: true
  Exclude:
    - app/policies/**

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - app/policies/**