---
development:
  DB_KEY: <`rake newkey:db`>
  DB_SALT: <`rake newsalt:db`>

test:
  DB_KEY: <`rake newkey:db`>
  DB_SALT: <`rake newsalt:db`>

production:
  DB_KEY: <`rake newkey:db`>
  DB_SALT: <`rake newsalt:db`>
