---
development:
  DB_KEY: <`rake generate:db_key`>
  DB_SALT: <`rake generate:db_salt`>
  MSG_KEY: <`rake generate:msg_key`>
  SENDGRID_API_KEY: <provision by heroku>
  VERIFY_KEY: <`rake generate:signing`>

test:
  DB_KEY: <`rake generate:db_key`>
  DB_SALT: <`rake generate:db_salt`>
  MSG_KEY: <`rake generate:msg_key`>
  SENDGRID_API_KEY: <provision by heroku>
  SIGNING_KEY: <`rake generate:signing`>
  VERIFY_KEY: <`rake generate:signing`>

production:
  DB_KEY: <`rake generate:db_key`>
  DB_SALT: <`rake generate:db_salt`>
  MSG_KEY: <`rake generate:msg_key`>
  SENDGRID_API_KEY: <provision by heroku>
  VERIFY_KEY: <`rake generate:signing`>
