---
development:
  DB_KEY: <`rake newkey:db`>
  DB_SALT: <`rake newsalt:db`>
  SENDGRID_API_KEY: <provision by heroku>

test:
  DB_KEY: <`rake newkey:db`>
  DB_SALT: <`rake newsalt:db`>
  SENDGRID_API_KEY: <provision by heroku>

production:
  DB_KEY: <`rake newkey:db`>
  DB_SALT: <`rake newsalt:db`>
  SENDGRID_API_KEY: <provision by heroku>
