---
development:
  DB_KEY: <`rake generate:db_key`>
  DB_SALT: <`rake generate:db_salt`>
  MSG_KEY: <`rake generate:msg_key`>
  SENDGRID_API_KEY: <provision by heroku>

test:
  DB_KEY: <`rake generate:db_key`>
  DB_SALT: <`rake generate:db_salt`>
  MSG_KEY: <`rake generate:msg_key`>
  SENDGRID_API_KEY: <provision by heroku>

production:
  DB_KEY: <`rake generate:db_key`>
  DB_SALT: <`rake generate:db_salt`>
  MSG_KEY: <`rake generate:msg_key`>
  SENDGRID_API_KEY: <provision by heroku>
